### ISSUE TITLE
Question about the evaluation.py

### ISSUE THREAD

**Issue by AAlkaid** [KiPA2022/kipa22#1]
Hi very nice work and thanks a lot for the baseline released. I have learnt a lot from it.

But I have a question about the evaluation.py. When I try to use the pretrained model directly to make the evalutation, there will be some mistakes.

For example, when i annotate code `net_S = train_net(n_epochs=n_epochs,...` and then use the code as follows.

`net_S = UNet3D(n_channels=1, n_classes=n_classes)`
`net_S.load_state_dict(torch.load("xxx/BASELINES/weights/UNet3D_epoch_200.pth"))`

The function HausdorffDistance in `evaluation.py` will return a 'FN' and 'FN' as result. But the hau in function HDAVD is float. 

So 
`Traceback (most recent call last):
  File "/data1/bzy/kipa22-main 2/BASELINES/test.py", line 143, in <module>
    HDAVD(model_name, n_classes, pred_dir, test_dir + '/label')
  File "/data1/bzy/kipa22-main 2/BASELINES/evaluation/evaluation.py", line 135, in HDAVD
    hau[c, i], hauAve[c, i] = HausdorffDistance(predict_suf, label_suf)
ValueError: could not convert string to float: 'FN'`  
will occur.

I used `0.nii.gz` as the test sample. I don't know how to solve it.

Hope to hear from you. Thanks. :)

**Comment by KiPA2022** [comment]
This error is raised by the absence of some structures’ segmentation results. We have optimized this code.

**Comment by AAlkaid** [comment]
> 
Thank you very much for your answer. The problem has been solved. 
Have a nice day!
