### ISSUE TITLE
Question about the pretrained model provided in this baseline

### ISSUE THREAD

**Issue by AAlkaid** [KiPA2022/kipa22#2]
Hiii, thanks a lot for the first question. But I have some new questions. 

1. I noticed that you have released three pretrained models for each baseline. And I do have some tests for them. Could you tell me t**he way for the division of training and test sets**?

2. In `BASELINE/Demo_densebiasnet.py line 117` the epoch may be 200 instead of 0?  

Hope to hear from you. Thank you so much.

**Comment by KiPA2022** [comment]
Thank you for your question. 
1. We used the whole training dataset (70 images) to train these baselines. Their performance on the open testing and closed testing datasets will be published when these datasets are released. You can try these baselines on these testing datasets when we open them.
2. Yes, this is a hyper-parameter, the number of epochs, in these baselines. You can set any value for it. In our training, we set it to 200, but this is a random setting.
