### ISSUE TITLE
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/2.nii.gz'

### ISSUE THREAD

**Issue by fengjiejiejiejie** [KiPA2022/kipa22#5]
Hi,
When I use the given  demo to run the docker image in my local machine, the error is occurred.
I see the '/output/' has already created at Dockerfile.

When run the following command:
docker run --rm --gpus all --runtime=nvidia --ipc=host -v /home/fengjie/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION_fj/input:/input/:ro -v /home/fengjie/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION_fj/output:/output/ my_docker_image_name

**Comment by newvoid7** [comment]
Could you please clearify what error occurred exactly?

**Comment by fengjiejiejiejie** [comment]
> Could you please clearify what error occurred exactly?

Thanks a lot. 
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/2.nii.gz'
It seems that the predicted results can not be written into output folder.

**Comment by newvoid7** [comment]
Have you created the output directory (in your case, /home/fengjie/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION_fj/output) in advance?

**Comment by fengjiejiejiejie** [comment]
> 

Yes. The disk also has free space.

**Comment by newvoid7** [comment]
Sorry, I have not met prolems like this before, I really don't know what causes this problem. I have confirmed that the dummy docker works perfectly fine on our machine. 

Maybe could you please try to output to another directory? Or have you confirmed that this dummy code without docker runs correctly on your machine? 

Or please try to remove the 'model_name' parameter in the code (although specified to blank string in predict.py), I don't know if this has something to do with the directory problem.

**Comment by fengjiejiejiejie** [comment]
Thanks for you kind response. After I changed the '/input' and '/output' to './input' and './output', the dummy code runs correctly without docker on my machine. Otherwise, the code will can't find the input folder.

When creating docker image, I use the '/input' and '/output', the code can read input images and generate the predicted nii file. But, the error is occurred when writing/saving.

**Comment by fengjiejiejiejie** [comment]
Hi,
(1) When I directly run the given demo without docker, the following error occurs.
(py39fjj) fengjie@FJ3090:~/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION$ python3 predict.py
Predict test data
Traceback (most recent call last):
  File "/home/fengjie/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION/predict.py", line 17, in <module>
    predict(net_S, save_path='/output', img_path='/input', model_name='')
  File "/home/fengjie/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION/Demo_densebiasnet.py", line 87, in predict
    image_filenames = [x for x in os.listdir(img_path) if is_image3d_file(x)]
FileNotFoundError: [Errno 2] No such file or directory: '/input'

(2) Then, I changed the '/input' and '/output' to './input' and './output', the code runs successfully without docker.

(3) When creating docker image, I use the **'/input' and '/output'**, the code can read input images successfully and generate the predicted nii file. But, the following error is occurred when writing/saving.
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/2.nii.gz'

**Comment by fengjiejiejiejie** [comment]
Hi,
I have changed the output folder, but the error is still occurred, the following is the result:
fengjie@FJ3090:~/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION_fj$ docker run --rm --gpus all --runtime=nvidia --ipc=host -v /home/fengjie/FJ_data/docker_io/image:/input/:ro -v /home/fengjie/FJ_data/docker_io/predict:/output/ simple_test1

image number: 3
2.nii.gz
1.nii.gz
0.nii.gz
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/2.nii.gz'
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/1.nii.gz'
** ERROR (nifti_image_write_hdr_img2): cannot open output file '/output/0.nii.gz'

It seems the local output path is correct, and the code can't find the docker '/output' folder.
Thanks a lot.

**Comment by fengjiejiejiejie** [comment]
Hi,
(1) I just use a simple demo to check the output folder (copy input image to output folder). The following is the simple version of predict.py.
########################################## predict.py ##########################################
import os
from os.path import join
import shutil


if __name__ == '__main__':

    save_path = '/output'
    img_path = '/input'

    image_filenames = [x for x in os.listdir(img_path)]
    print('image number:', len(image_filenames))

    if not os.path.exists(save_path):
        print('output dir is none!')
        os.makedirs(save_path)

    for imagename in image_filenames:
        print(imagename)
        shutil.copy(join(img_path, imagename), join(save_path, imagename))
####################################################################################

(2) Then I run the docker.
fengjie@FJ3090:~/FJ_data/kipa22/kipa22-main/DUMMY_SUBMISSION_fj$ docker run --rm --gpus all --runtime=nvidia --ipc=host -v /home/fengjie/FJ_data/docker_io/image:/input/:ro -v /home/fengjie/FJ_data/docker_io/predict:/output/ my_docker_image_name

image number: 3
2.nii.gz
Traceback (most recent call last):
  File "/opt/code/predict.py", line 21, in <module>
    shutil.copy(join(img_path, imagename), join(save_path, imagename))
  File "/usr/local/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/output/2.nii.gz'


The output folder is exsited, I guess it could be a permission issue?
Thanks a lot!

**Comment by newvoid7** [comment]
This is weird. Maybe you could try "sudo docker run ..." and see what will happen?

**Comment by fengjiejiejiejie** [comment]
> This is weird. Maybe you "sudo docker run ..." and see what will happen?

Thanks for your response. I will try again later.

**Comment by fengjiejiejiejie** [comment]
>

**Comment by fengjiejiejiejie** [comment]
> This is weird. Maybe you could try "sudo docker run ..." and see what will happen?

Hi,
Thank you a lot for your kind response. I have solved the problem after I changed the local output path:
 (-v /home/fengjie/FJ_data/docker_io/predict:/output/ --> -v LOCAL_OUTPUT:/output/)
The predicted results are saved at /var/lib/docker/volumes/LOCAL_OUTPUT
If can't open the /docker folder, just use the 'sudo chmod 777 docker' command. I hope it could help others.

**Comment by newvoid7** [comment]
Thank you as well for the useful suggestion. It seems to me that if the output directory is not owned by the user who runs the docker container, this error will occur. Anyway, thanks for your interest in KiPA22 Challenge!
