### ISSUE TITLE
Question about WW and WL

### ISSUE THREAD

**Issue by Bruce1973** [KiPA2022/kipa22#6]
Thank you for your great work. I found the pixel value of the images range from 0 to 2048, could you provide the WW and WL in the preprocess stage?

**Comment by newvoid7** [comment]
Thanks for your attention. For preprocessing of the challenge dataset, we did not set the WW and WL , we just simply cropped the kidney area. The grayscale value of the images are defined as follows: 
Grayscale value = CT value + 1024.

**Comment by Bruce1973** [comment]
Got it! Thanks!
